language: python
python:
   - 2.6
   - 2.7
   - 3.3
   - 3.4
# mock/multiprocessing are only necessary for testing
install:
   - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then
     pip install -rdev_requirements26.txt;
     else
     pip install -rdev_requirements.txt;
     fi

# command to run tests, e.g. python setup.py test
script:
  - python -m bentomakerlib.bentomaker distcheck;
  - python check_examples.py
