language: python
python:
   - 2.5
   - 2.6
   - 2.7
   - 3.2
# mock/multiprocessing are only necessary for testing
install: pip install mock  multiprocessing
# command to run tests, e.g. python setup.py test
script:  python -m bentomakerlib.bentomaker distcheck
