language: python
python:
   - 2.5
   - 2.6
   - 2.7
   - 3.2
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install mock 
# command to run tests, e.g. python setup.py test
script:  python -m bentomakerlib.bentomaker distcheck
